/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.sma.mobile.android;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int blue=0x7f020000;
        public static final int empty=0x7f020001;
        public static final int glow=0x7f020002;
        public static final int green=0x7f020003;
        public static final int icon=0x7f020004;
        public static final int lion=0x7f020005;
        public static final int orange=0x7f020006;
        public static final int pink=0x7f020007;
        public static final int recticle=0x7f020008;
        public static final int recticle_blue=0x7f020009;
        public static final int recticle_green=0x7f02000a;
        public static final int recticle_orange=0x7f02000b;
        public static final int recticle_pink=0x7f02000c;
        public static final int recticle_red=0x7f02000d;
        public static final int recticle_violet=0x7f02000e;
        public static final int recticle_white=0x7f02000f;
        public static final int recticle_yellow=0x7f020010;
        public static final int red=0x7f020011;
        public static final int violet=0x7f020012;
        public static final int white=0x7f020013;
        public static final int yellow=0x7f020014;
    }
    public static final class id {
        public static final int board=0x7f050000;
        public static final int myTableLayout=0x7f050001;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int hello=0x7f040000;
        public static final int help=0x7f040002;
    }
}
